// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWxrkuupJYBstolY-ugLk-BigoWlS1kdo',
    appId: '1:65173926856:web:75b7a4d689023b6cd946fd',
    messagingSenderId: '65173926856',
    projectId: 'elec3-b4180',
    authDomain: 'elec3-b4180.firebaseapp.com',
    storageBucket: 'elec3-b4180.firebasestorage.app',
    measurementId: 'G-3L955QFBQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-tBmFPhbRjq6YucoVDBhUOeN71602vbU',
    appId: '1:65173926856:android:4ea9051eb56ec975d946fd',
    messagingSenderId: '65173926856',
    projectId: 'elec3-b4180',
    storageBucket: 'elec3-b4180.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkxekmgFIaQhtgRb-L71MODkS3MV2i0u8',
    appId: '1:65173926856:ios:6d63cf87635cf33dd946fd',
    messagingSenderId: '65173926856',
    projectId: 'elec3-b4180',
    storageBucket: 'elec3-b4180.firebasestorage.app',
    iosBundleId: 'com.example.elec3proj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkxekmgFIaQhtgRb-L71MODkS3MV2i0u8',
    appId: '1:65173926856:ios:6d63cf87635cf33dd946fd',
    messagingSenderId: '65173926856',
    projectId: 'elec3-b4180',
    storageBucket: 'elec3-b4180.firebasestorage.app',
    iosBundleId: 'com.example.elec3proj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWxrkuupJYBstolY-ugLk-BigoWlS1kdo',
    appId: '1:65173926856:web:92042295977fce5dd946fd',
    messagingSenderId: '65173926856',
    projectId: 'elec3-b4180',
    authDomain: 'elec3-b4180.firebaseapp.com',
    storageBucket: 'elec3-b4180.firebasestorage.app',
    measurementId: 'G-09K13CFWRB',
  );
}
